In [ ]:
NUMPY:


In [5]:
import numpy as np
a=np.array([1,5,7])
a1=np.array([[1,5,7],[2,5,9]])
print(a)
print(a1)
print("print me 2nd index 3rd value",a1[1][2])
print(np.arange(10))
print(a.ndim)
print(a1.ndim)
a.shape
print(a1.shape)
len(a1)

[1 5 7]
[[1 5 7]
 [2 5 9]]
print me 2nd index 3rd value 9
[0 1 2 3 4 5 6 7 8 9]
1
2
(2, 3)


2

In [11]:
import numpy as np
matrix_seq=np.arange(1,17).reshape(4,4)
print("4*4 matrix with numbers 1 to 16:")
print(matrix_seq)


4*4 matrix with numbers 1 to 16:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:

L=range(1000)
%timeit a**2

671 ns ± 20.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
import numpy as np
L=np.arange(1000)
%timeit L**2

1.76 µs ± 8.64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
import numpy as np
a=np.array([[9,3,7],[1,3,9]])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))
print(a[1][1])

a[1][1]=6
print(a)

[[9 3 7]
 [1 3 9]]
2
(2, 3)
2
3
[[9 3 7]
 [1 6 9]]


In [20]:
ls=np.array([[[1,3,2],[2,6,3]],[[5,7,6],[3,7,2]]])
print(ls)
ls[0][1][2]
print(ls.shape)
print(ls.ndim)

[[[1 3 2]
  [2 6 3]]

 [[5 7 6]
  [3 7 2]]]
(2, 2, 3)
3


In [21]:
a=np.arange(1,10,3)
a

array([1, 4, 7])

In [22]:
ls=np.linspace(1,2,4)
ls

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [23]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a=np.eye(2,3)
a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [28]:
a=np.diag([1,2,3,5,6])
a.shape
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [29]:
a=np.random.rand(5)
a

array([0.92893164, 0.63096686, 0.88392296, 0.20129766, 0.58550582])

In [30]:
a=np.arange(10)
a.dtype


dtype('int32')

In [32]:
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [37]:
d=np.array([1+2j,2+4j])
print(d.dtype)
d

complex128


array([1.+2.j, 2.+4.j])

In [38]:
b=np.array((True,False,True,False))
print(b.dtype)

bool


In [39]:
s=np.array(['sam','jon'])
print(s.dtype)

<U3


In [40]:
a=np.arange(10)
print(a[5])
a

5


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [46]:
b=np.arange(5)
a[5:]=b[::-1]
b
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [48]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([2,3,4]),(7,8,9)])
print(a+b)

SyntaxError: unmatched ']' (4104885553.py, line 3)

In [49]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [53]:
print(id(a))
print(id(b))


2850700340240
2850700331888


In [54]:
c=a[::3]
c

array([0, 3, 6, 9])